### ISSUE TITLE
GPT4

### ISSUE THREAD

**Issue by marcj** [j0rd1smit/obsidian-copilot-auto-completion#12]
Would it be possible to allow GPT-4 as model? 

Thanks for this great plugin!

**Comment by j0rd1smit** [comment]
Yeah, it is possible, but the response type will be slower while costs are higher.
Initially, I disabled it because the response type was unbearably slow. However, it seems like, in the last couple of months, OpenAI has made their API faster/more efficient.
So, I will add the option.
Currently, it is hectic at my day job, but from next week onwards, I should have time for it.

**Comment by WilliamsJack** [comment]
I've been running GPT-4 Turbo for a couple of weeks and it seems to work well - #13

**Comment by j0rd1smit** [comment]
Thanks to #13 you can now pick your own openai model including gpt-4 (`gpt-4-1106-preview`).
Thanks @WilliamsJack
