### ISSUE TITLE
consider to support the github copilot

### ISSUE THREAD

**Issue by BobbyJonas** [j0rd1smit/obsidian-copilot-auto-completion#15]
Although this is a great plugin and runs very well on my Obsidian, it would be better if support for Github Copilot could be considered to be added. 

As we know, the Github released [their official copilot for vim](https://github.com/github/copilot.vim). So I think the two may have something in common.

**Comment by j0rd1smit** [comment]
I would love to do that, but Github does make their copilot APIs publicly available. To access them, you have to do all kinds of hacky things, as discussed in [this StackOverflow post](https://stackoverflow.com/questions/76741410/how-to-invoke-github-copilot-programmatically).  Adding this feature would be an incredible maintenance burden since it could break anytime.

So, sadly, I have to close this for now until it becomes publicly available.
