### ISSUE TITLE
Post-Processing to Exclude Existing Text from Suggestions

### ISSUE THREAD

**Issue by WilliamsJack** [j0rd1smit/obsidian-copilot-auto-completion#9]
# Problem
Sometimes the model will return a completion that includes existing text. For example, asking for a suggestion in the middle of a sentence may return a completion with the first part of the sentence along with the suggestion.

## Problem examples
**User's prefix text is returned.**
![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/30068301/9f41031d-2c04-4773-8826-81605348e03f)

**User's suffix text is returned, including `<mask/>`.**
![image](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/assets/30068301/cb5ef6aa-daae-4a8b-ba4d-9ced2817c0cc)

# Solution
If existing text is returned, it should be removed before showing the suggestion to the user. While we could also give more robust instructions to the LLM, implementing this as a post-processing step will ensure it's caught every time, as it will not rely on the model's behaviour during generation and whether the LLM is following instructions properly.

# Further Ideas
If a significant portion or the entirety of the suggestion consists of existing text (such as in the second example image), we could automatically trigger a retry and generate a new suggestion. This could be a clean, blind retry where the model has no knowledge of its mistake, or we could resend the previous prompt and the models completion, this time with an additional system message stating the problem with the first attempt. This would need some testing - we wouldn't want the model to apologise in the middle of its next suggestion!

**Comment by j0rd1smit** [comment]
This is indeed a throne in my sight. I indeed want this fix. However, the overlap detection remains rather tricky since there are often minimalistic differences that cause the [naive overlap post processor](https://github.com/j0rd1smit/obsidian-copilot-auto-completion/blob/master/src/prediction_services/post_processors/remove_overlap.ts) not to work. I have some ideas I want to try out that might solve some issues. I should have some time for it next week.

I first want to try a more heuristic approach to avoid making too many API calls. However, we could do a similarity check to decide that a new generation is needed. However, that will be a last resort if the additional heuristic approaches don't work.

If you have a list of failure examples, please share them here so that I already have some test cases.
